/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrojogojava;

import javax.swing.JOptionPane;

/**
 *
 * @author PREDATOR
 */
public class TelaInicialComum extends javax.swing.JDialog {
    Usuario logado = new Usuario();
    
    /**
     * Creates new form TelaInicialComum
     */
    public TelaInicialComum(java.awt.Frame parent, boolean modal, Usuario logado) {
        super(parent, modal);
        initComponents();
        this.logado = logado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCarteira = new javax.swing.JButton();
        botaoJogos = new javax.swing.JButton();
        BotaoDesconectar = new javax.swing.JButton();
        botaoLoja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Inicial");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Scrimin Games");

        botaoCarteira.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoCarteira.setText("Sua Carteira");
        botaoCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarteiraActionPerformed(evt);
            }
        });

        botaoJogos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoJogos.setText("Biblioteca");
        botaoJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogosActionPerformed(evt);
            }
        });

        BotaoDesconectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotaoDesconectar.setText("Desconectar");
        BotaoDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDesconectarActionPerformed(evt);
            }
        });

        botaoLoja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoLoja.setText("Loja");
        botaoLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLojaActionPerformed(evt);
            }
        });

        jLabel2.setText("Logado com");

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoCarteira)
                                .addGap(73, 73, 73)
                                .addComponent(botaoJogos)
                                .addGap(9, 9, 9))
                            .addComponent(BotaoDesconectar))
                        .addGap(77, 77, 77)
                        .addComponent(botaoLoja)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCarteira)
                    .addComponent(botaoJogos)
                    .addComponent(botaoLoja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(BotaoDesconectar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogosActionPerformed
        try{
               TelaExibeBiblioteca.abrir(logado); 
  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhum Jogo adquirido");
        }
    }//GEN-LAST:event_botaoJogosActionPerformed

    private void botaoCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarteiraActionPerformed
        TelaCarteira.abrir(logado);
    }//GEN-LAST:event_botaoCarteiraActionPerformed

    private void BotaoDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDesconectarActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }//GEN-LAST:event_BotaoDesconectarActionPerformed

    private void botaoLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLojaActionPerformed
        try{
               TelaExibeLoja.abrir(logado); 
  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nenhum Jogo Disponivel para compra no momento!");
        }
    }//GEN-LAST:event_botaoLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void abrirJanelaInicial(Usuario logado) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInicialComum dialog = new TelaInicialComum(new javax.swing.JFrame(), true, logado);
                dialog.labelLogin.setText(logado.getUsername());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDesconectar;
    private javax.swing.JButton botaoCarteira;
    private javax.swing.JButton botaoJogos;
    private javax.swing.JButton botaoLoja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelLogin;
    // End of variables declaration//GEN-END:variables
}
