package cadastrojogojava;


import java.util.LinkedList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PREDATOR
 */
public class TelaCadastro extends javax.swing.JDialog {
    Repositorio r;
    Jogos j = new Jogos();
    /**
     * Creates new form telaCadastro
     */
    public TelaCadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Repositorio getR() {
        return r;
    }

    public void setR(Repositorio r) {
        this.r = r;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldNome = new javax.swing.JTextField();
        fieldValor = new javax.swing.JTextField();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        labelCadastarJogo = new javax.swing.JLabel();
        labelNome1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fieldQuant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Jogos");
        setResizable(false);

        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });

        botaoOk.setText("Ok");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        labelCadastarJogo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        labelCadastarJogo.setText("Cadastrar Jogo");

        labelNome1.setText("Nome:");

        jLabel3.setText("Preço:");

        jLabel1.setText("R$");

        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade:");

        fieldQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoOk)
                .addGap(163, 163, 163))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCancelar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(labelCadastarJogo)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(labelNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldQuant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastarJogo)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome1)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoOk)
                    .addComponent(ButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
       fieldNome.setText("");
       fieldValor.setText(""); 
       
       JOptionPane.showMessageDialog(null, "Cadastro Cancelado.");
    }//GEN-LAST:event_botaoCancelarActionPerformed

    
    
    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
       LinkedList<Jogos> lojinha = Banco.listaJogos();
        int cont = lojinha.size() + 1;
        
        for(Jogos j: lojinha){
                    while(j.getId() == cont){
                        cont++;
                    }
                }
        try{
        j = new Jogos();
        j.setJogos(fieldNome.getText());
        j.setPreco(Integer.parseInt(fieldValor.getText()));
        j.setId(cont);
        j.setQuantidade(Integer.parseInt(fieldQuant.getText()));
        if(verificaSeExiste(lojinha)){
            Banco.salvarJogos(j);
            
            
        fieldNome.setText("");
        fieldValor.setText(""); 
        fieldQuant.setText("");
        
        JOptionPane.showMessageDialog(null, "O jogo foi cadastrado");
        }
        else {
           Banco.atualizaBancoJogos(j);
        }
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, "Por favor preencha adequadamente os dados.");  
        }
    }//GEN-LAST:event_botaoOkActionPerformed

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorActionPerformed

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void fieldQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldQuantActionPerformed
    
    public boolean verificaSeExiste(LinkedList<Jogos> lojinha){
        boolean r = true;
        for (Jogos j : lojinha) {
            if((j.getPreco() == Integer.parseInt(fieldValor.getText())) && j.getJogos().equals(fieldNome.getText() )) {
            r = false;
            j.incrementaQuantidade();
            JOptionPane.showMessageDialog(null, "Foi adicionado a quantidade");
            fieldNome.setText("");
            fieldValor.setText(""); 
            break;

             }    
             else if((j.getPreco() != Integer.parseInt(fieldValor.getText())) && j.getJogos().equals(fieldNome.getText() )){
               r = false;
               JOptionPane.showMessageDialog(null, "Esse jogo já está cadastrado com outro preço");
               break;
            }
        }        
        return r;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldQuant;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCadastarJogo;
    private javax.swing.JLabel labelNome1;
    // End of variables declaration//GEN-END:variables
}
